# Generated by Django 5.1.1 on 2024-10-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('russia', models.ImageField(upload_to='logo_image/')),
                ('s_russia', models.ImageField(upload_to='logo_image/')),
                ('bell', models.ImageField(upload_to='logo_image/')),
                ('s_bell', models.ImageField(upload_to='logo_image/')),
                ('Us', models.ImageField(upload_to='logo_image/')),
                ('s_us', models.ImageField(upload_to='logo_image/')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('bio2', models.TextField(verbose_name='Bio')),
                ('bio3', models.TextField(verbose_name='Bio')),
                ('bio4', models.TextField(verbose_name='Bio')),
                ('bio5', models.TextField(verbose_name='Bio')),
                ('bio6', models.TextField(verbose_name='Bio')),
            ],
        ),
    ]
